---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

***Describe how you have improved as a practitioner and student of data science this quarter through your work in the course.***

-   Focus specifically on data science concepts and the skills we employed in learning them, not a laundry list of topics that you learned (those are in the syllabus, so I know them already).

-   Focus on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth and explain how this artifact shows growth in the way you are describing.

During the course of this quarter, I improved as a practitioner of data science in many different ways. Prior to this class, I was not very aware of concepts in data science such as data cleaning within data sets to uncover trends or information that the data set could be hiding. But throughout the time I spent in this class, learning about the capability of R to be able to sift through data, change aspects of data sets, and ultimately identify patterns or information, I found out about the true capability of R. Now, I am more aware of what I should look to do when I am given a data set. Instead of taking it at face value, I aim to look at what mistakes and what missing information is present in such a data set, and if I should get rid of specific values to make the data set easier to look at when trying to answer a specific statistical question.

An area of growth that I had in my portfolio compared to the beginning of the year, was in the data visualization section. Prior to this course, I had a basic understanding of how to create plots within R, to provide a simple graph of a data set. However, after taking this course, and learning about the different capabilities of ggplot, I managed to be able to do new things such as modifying the text size of the plots, working with non-standard colors, and adding new levels of creativity into plots that I hadn't considered before.

Another area of growth that I had in my portfolio compared to before taking this course was practicing tidy code. Before this course, I wouldn't really put a lot of thought into making my code look tidy at all, rather, I would write lines and lines of code just to get the job done. Throughout the course of this class, I learned to be more disciplined and do the little things such as starting a new line after a comma. This helped improve the tidyness of my code by a large amount, as now I feel it is more readable than what I was typing in before.
