---
title: "The Power of Efficiency"
format: html
editor: visual
---

As we’ve said in the class efficiency is a pivotal component of statistical computing (and data science). In this essay, give an explanation of what that term “efficiency” means in relation to statistical computing and describe some places where you encountered efficiency and understood its importance. Your essay should address the following questions:

-   What is the definition of “efficiency”?

-   What does efficiency look like in statistical computing / data science?

-   What does efficiency allow you to do?

-   Why is efficiency important?

-   Where did you encounter efficiency, and what were some [“a-ha” moments](https://www.merriam-webster.com/dictionary/aha%20moment) you had about efficiency? (For the latter, tie each a-ha moment to an artifact in the portfolio.)

Efficiency is defined to be achieving maximum productivity with minimum wasted effort. In statistical computing, being efficient means creating code that isn't overtly long and takes up large amounts of memory to complete a task. Being efficient allows us to complete tasks quickly without much effort, and it allows us to spend more time on more pressing tasks. Efficiency is important because we need to find ways to complete tasks to get a job done, but we also need to do it in a way so that we aren't wasting too much resources on finishing a task. In this class, I encountered efficiency when learning about how we could iterate a function to complete a task much quicker without having to create a large dplyr pipeline or call a function multiple times. This moment was connected to the pmap function, where we could pass a number of arguments and get one function to be applied to all of those arguments.
